
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ronit
 */
public class Autolotefrm extends javax.swing.JFrame {
    int bandpri=0;
    int x=0;
    int eliminarCiclo=0;

    ProyAutolote pro = new ProyAutolote();
    private void iniciar() {
    
    pro.Inicilizar();    
    }

    private void cargarDats() {
       pro.Datos();
    }

    private void limpiarcampos() {
                    getTxtcodigo().setText("");
            getTxtplaca().setText("");
            getTxtmarca().setText("");
            getTxttipo().setText("");
            getTxtcolor().setText("");
            getTxtaño().setText("");
            getTxtprecio().setText("");    
    }

    private int calcularCant() {
        for (int i = 1; i < pro.X.length; i++) {
            if (pro.X[i].getCodAuto()==null) {
                x=i;
                return x;

            }
        }
        return 0;
    }

    private void remover() {
        for (int i = 0; i <=x; i++) {
            model.removeRow(0);
        }}

    private void cargarArchivo() {
       String codigo,placa,marca,tipo,color,año,precio;
        String dir ="datos.txt";
        
        Scanner linea = null;
        
        File doc_le = new File(dir);
        
        try {
            linea = new Scanner(doc_le);
            while (linea.hasNextLine()) {                
                codigo=linea.nextLine();
                placa=linea.nextLine();
                marca=linea.nextLine();
                tipo=linea.nextLine();
                color=linea.nextLine();
                año=linea.nextLine();
                precio=linea.nextLine();
                
                model.addRow(new Object[]{codigo,placa,marca,tipo,color,año,precio});
            }
        } catch (Exception e) {
        }
        
    
    }
    
    
    
    class BufferedReader {
public BufferedReader(FileReader fileReader) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

public String readLine() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

public void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
    
    
public class Archivos_1 extends javax.swing.JFrame {
    DefaultTableModel modelo;
    String[] Titulo = {"CODAUTO","PLACA","MARCA","TIPO","COLOR","AÑO","PRECIO"};
    String[] Registro = new String[7];
    String FilaSeleccionada;
    int FilaSelec;
    public Archivos_1() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel(null,Titulo);
        jTable1.setModel(modelo);
    }
}
    /**
     * Creates new form Autolote
     */
    public Autolotefrm() {
        initComponents();
        model=(DefaultTableModel)this.jTable1.getModel();
    }
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        Inicializar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        VerRegistros = new javax.swing.JButton();
        LeerArchivo = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        NuevaLinea = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inicializar.setText("Inicializar");
        Inicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicializarActionPerformed(evt);
            }
        });

        jButton2.setText("Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        VerRegistros.setText("Ver Registros");
        VerRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerRegistrosActionPerformed(evt);
            }
        });

        LeerArchivo.setText("Leer Archivo");
        LeerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerArchivoActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        NuevaLinea.setText("Nuevo");
        NuevaLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaLineaActionPerformed(evt);
            }
        });

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Marca");

        jLabel3.setText("Placa");

        jLabel4.setText("Tipo");

        jLabel5.setText("Color");

        jLabel6.setText("Año");

        jLabel7.setText("Precio");

        jButton9.setText("Agregar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Eliminar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("<< Primero");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("< Anterior");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Siguiente >");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Ultimo >>");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Listar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Eliminar Reg");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel8.setText("Filtro:");

        jButton17.setText("Filtrar por Color");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Filtrar por Marca");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Placa", "Marca", "Tipo", "Color", "Año", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton19.setText("Ordenar precio");

        jButton20.setText("Ordenar Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(Inicializar)
                                    .addComponent(jButton9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(VerRegistros))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addComponent(jButton10))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(LeerArchivo)
                                .addGap(18, 18, 18)
                                .addComponent(Guardar)
                                .addGap(87, 87, 87)
                                .addComponent(NuevaLinea))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)))
                                    .addComponent(jButton11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton12)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton13)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton14)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inicializar)
                    .addComponent(jButton2)
                    .addComponent(VerRegistros)
                    .addComponent(LeerArchivo)
                    .addComponent(Guardar)
                    .addComponent(NuevaLinea)
                    .addComponent(jButton8))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton12)
                            .addComponent(jButton13)
                            .addComponent(jButton14))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerArchivoActionPerformed
       cargarArchivo();
    }//GEN-LAST:event_LeerArchivoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
    try {
        FileWriter salvar = new FileWriter("datos.txt");
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            salvar.write(model.getValueAt(i,0).toString()+"\n");
            salvar.write(model.getValueAt(i,1).toString()+"\n");
            salvar.write(model.getValueAt(i,2).toString()+"\n");
            salvar.write(model.getValueAt(i,3).toString()+"\n");
            salvar.write(model.getValueAt(i,4).toString()+"\n");
            salvar.write(model.getValueAt(i,5).toString()+"\n");
            salvar.write(model.getValueAt(i,6).toString()+"\n");
        }
        salvar.close();
        JOptionPane.showMessageDialog(null,"Datos guardados");
        }catch (Exception x){
            System.out.println("error1");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void InicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicializarActionPerformed
        iniciar();
        JOptionPane.showMessageDialog(null,"Datos Inicializados"); 
    }//GEN-LAST:event_InicializarActionPerformed

    private void NuevaLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaLineaActionPerformed
        limpiarcampos();

    
    }//GEN-LAST:event_NuevaLineaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       String codigo,placa,marca,tipo,color,año,precio;
       int bandera=0;
        for (int i = 1; i <=x; i++) {
           String prueba1=getTxtcodigo().getText();
           String prueba2=pro.X[i].getCodAuto();
            if (prueba1.equals(prueba2)) {
                JOptionPane.showMessageDialog(null,"Registro no puede ser agregado, codigo ya existe.");
                bandera=1;
                break;
            }
        }
        if(bandera==0){
                String actual=""+getTxtcodigo().getText();
                String real=(actual.substring(1));
                int fin= Integer.parseInt(real)-1;
                codigo=getTxtcodigo().getText();
                placa=getTxtplaca().getText();
                marca=getTxtmarca().getText();
                tipo=getTxttipo().getText();
                color=getTxtcolor().getText();
                año=getTxtaño().getText();
                precio=getTxtprecio().getText();
                x++;
                pro.X[x].setCodAuto(codigo);
                pro.X[x].setPlaca(placa);
                pro.X[x].setMarca(marca);
                pro.X[x].setTipo(tipo);
                pro.X[x].setColor(color);
                pro.X[x].setAño(Integer.parseInt(año));
                pro.X[x].setPrecio(Integer.parseInt(precio));
                model.addRow(new Object[]{codigo,placa,marca,tipo,color,año,precio});
                JOptionPane.showMessageDialog(null,"Agregado correctamente.");
                
            }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      
        int bandera=2;
        for (int i = 1; i <=x; i++) {
           
           String prueba1=getTxtcodigo().getText();
           String prueba2=model.getValueAt(i-1,0).toString();
            if (prueba1.equals(prueba2)) {
                System.out.println("prueba 1 es :"+prueba1+prueba2);
                JOptionPane.showMessageDialog(null,"Eliminando registro . . .");
                        String real=(prueba1.substring(1));
                        int fin= Integer.parseInt(real)-1;
                        System.out.println("el otro es"+prueba1);
                        model.removeRow(i-1);
                bandera=1;
                break;
            }
        }
       

        
                
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarDats();
        x=calcularCant();
       JOptionPane.showMessageDialog(null,"Datos cargados");

        
        System.out.println("el tamaño es " +x);
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VerRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRegistrosActionPerformed
            String codigo,placa,marca,tipo,color,año,precio;
            codigo=pro.X[1].getCodAuto();
            placa=pro.X[1].getPlaca();
            marca=pro.X[1].getMarca();
            tipo=pro.X[1].getTipo();
            color=pro.X[1].getColor();
            año=""+(pro.X[1].getAño());
            precio=""+(pro.X[1].getPrecio());
            
            getTxtcodigo().setText(codigo);
            getTxtplaca().setText(placa);
            getTxtmarca().setText(marca);
            getTxttipo().setText(tipo);
            getTxtcolor().setText(color);
            getTxtaño().setText(año);
            getTxtprecio().setText(precio);
    }//GEN-LAST:event_VerRegistrosActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String codigo,placa,marca,tipo,color,año,precio;
            codigo=pro.X[1].getCodAuto();
            placa=pro.X[1].getPlaca();
            marca=pro.X[1].getMarca();
            tipo=pro.X[1].getTipo();
            color=pro.X[1].getColor();
            año=""+(pro.X[1].getAño());
            precio=""+(pro.X[1].getPrecio());
            
            getTxtcodigo().setText(codigo);
            getTxtplaca().setText(placa);
            getTxtmarca().setText(marca);
            getTxttipo().setText(tipo);
            getTxtcolor().setText(color);
            getTxtaño().setText(año);
            getTxtprecio().setText(precio);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       String codigo,placa,marca,tipo,color,año,precio;

            codigo=pro.X[x-1].getCodAuto();
            placa=pro.X[x-1].getPlaca();
            marca=pro.X[x-1].getMarca();
            tipo=pro.X[x-1].getTipo();
            color=pro.X[x-1].getColor();
            año=""+(pro.X[x-1].getAño());
            precio=""+(pro.X[x-1].getPrecio());
            
            getTxtcodigo().setText(codigo);
            getTxtplaca().setText(placa);
            getTxtmarca().setText(marca);
            getTxttipo().setText(tipo);
            getTxtcolor().setText(color);
            getTxtaño().setText(año);
            getTxtprecio().setText(precio);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String actual=""+getTxtcodigo().getText();
        String real=(actual.substring(1));
        int fin= Integer.parseInt(real)-1;
        String codigo,placa,marca,tipo,color,año,precio;
        if (fin<=0) {
            JOptionPane.showMessageDialog(null,"Ya llegaste al primero");
        }else{
            codigo=pro.X[fin].getCodAuto();
            placa=pro.X[fin].getPlaca();
            marca=pro.X[fin].getMarca();
            tipo=pro.X[fin].getTipo();
            color=pro.X[fin].getColor();
            año=""+(pro.X[fin].getAño());
            precio=""+(pro.X[fin].getPrecio());
            
            getTxtcodigo().setText(codigo);
            getTxtplaca().setText(placa);
            getTxtmarca().setText(marca);
            getTxttipo().setText(tipo);
            getTxtcolor().setText(color);
            getTxtaño().setText(año);
            getTxtprecio().setText(precio);
        }
               
                
            
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String actual=""+getTxtcodigo().getText();
        String real=(actual.substring(1));
        int fin= Integer.parseInt(real)+1;
        String codigo,placa,marca,tipo,color,año,precio;
        System.out.println("fin es "+ fin);
        if (fin>(x-1)) {
            JOptionPane.showMessageDialog(null,"Ya llegaste al ultimo");
        }else{
            codigo=pro.X[fin].getCodAuto();
            placa=pro.X[fin].getPlaca();
            marca=pro.X[fin].getMarca();
            tipo=pro.X[fin].getTipo();
            color=pro.X[fin].getColor();
            año=""+(pro.X[fin].getAño());
            precio=""+(pro.X[fin].getPrecio());
            
            getTxtcodigo().setText(codigo);
            getTxtplaca().setText(placa);
            getTxtmarca().setText(marca);
            getTxttipo().setText(tipo);
            getTxtcolor().setText(color);
            getTxtaño().setText(año);
            getTxtprecio().setText(precio);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       String codigo,placa,marca,tipo,color,año,precio;
       int bandera=0;
        for (int i = 1; i <=x; i++) {
           String prueba1=getTxtcodigo().getText();
           String prueba2=pro.X[i].getCodAuto();
            if (prueba1.equals(prueba2)) {
                JOptionPane.showMessageDialog(null,"Registro encontrado.");
                getTxtplaca().setText(pro.X[i].getPlaca());
                getTxtmarca().setText(pro.X[i].getMarca());
                getTxttipo().setText(pro.X[i].getTipo());
                getTxtcolor().setText(pro.X[i].getColor());
                getTxtaño().setText(""+pro.X[i].getAño());
                getTxtprecio().setText(""+pro.X[i].getPrecio());
                bandera=1;
                break;
            }
        }
        if (bandera==0) {
            JOptionPane.showMessageDialog(null,"Registro no existe.");
        }
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        remover();
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int contadorfin=0;
        
        if (bandpri==1){
            System.out.println("es zxxxxx . . . "+contadorfin);
           contadorfin=0;
           
        
            for (int i = 1; i < pro.X.length-1; i++) {
            if (pro.X[i].getCodAuto()==null) {
                x=i;
            }
        }
           System.out.println("entre a cargar el archivo");
       System.out.println("x es " +x);
       String codigo,placa,marca,tipo,color,año,precio;
       String prueba1=getjTextField8().getText();
       int bandera=0;
       int cont=x;
        for (int i = 1; i <=x-1; i++) {
           //String prueba1=getjTextField8().getText();
           String prueba2=pro.X[i].getColor();
            System.out.println("El registro " + pro.X[i].getCodAuto() + " ES:"+prueba1+prueba2);
            if (prueba1.equals(prueba2)) {
                System.out.println("entre");
                codigo=pro.X[i].getCodAuto();
                placa=pro.X[i].getPlaca();
                marca=pro.X[i].getMarca();
                tipo=pro.X[i].getTipo();
                color=pro.X[i].getColor();
                año=""+pro.X[i].getAño();
                precio=""+pro.X[i].getPrecio();

                pro.X[x].setCodAuto(codigo);
                pro.X[x].setPlaca(placa);
                pro.X[x].setMarca(marca);
                pro.X[x].setTipo(tipo);
                pro.X[x].setColor(color);
                pro.X[x].setAño(Integer.parseInt(año));
                pro.X[x].setPrecio(Integer.parseInt(precio));
                model.addRow(new Object[]{codigo,placa,marca,tipo,color,año,precio});
                contadorfin++;
            }else{
                 //CODIGO DESPUES
            }
        }
        int tamanio=0;
        do {            
            tamanio++;
        } while (pro.X[tamanio]!=null);
           System.out.println("el tamaño es " + tamanio);
           System.out.println("el tamaño anterior es"+x);
           System.out.println("los que falta eliminar son"+eliminarCiclo);
            int eliminar=tamanio-cont-1; 
            System.out.println("ando elimnando" + eliminar);
                for (int k = 1; k <=eliminar+eliminarCiclo; k++) {
                    System.out.println("elimine"+ k);
                    model.removeRow(0);
                }
                   
        eliminarCiclo=0;
        eliminarCiclo=contadorfin;
        //Contar los que habian antes de iniciar la funcion eliminar y eliminar ese numero de los actuales.
  
       }else{
            
           contadorfin=0; 
           bandpri=1;
       System.out.println("entre a cargar el archivo");
       System.out.println("x es " +x);
       String codigo,placa,marca,tipo,color,año,precio;
       String prueba1=getjTextField8().getText();
       int bandera=0;
       int cont=x;
        for (int i = 1; i <=x-1; i++) {
           //String prueba1=getjTextField8().getText();
           String prueba2=pro.X[i].getColor();
            System.out.println("El registro " + pro.X[i].getCodAuto() + " ES:"+prueba1+prueba2);
            if (prueba1.equals(prueba2)) {
                System.out.println("entre");
                codigo=pro.X[i].getCodAuto();
                placa=pro.X[i].getPlaca();
                marca=pro.X[i].getMarca();
                tipo=pro.X[i].getTipo();
                color=pro.X[i].getColor();
                año=""+pro.X[i].getAño();
                precio=""+pro.X[i].getPrecio();

                pro.X[x].setCodAuto(codigo);
                pro.X[x].setPlaca(placa);
                pro.X[x].setMarca(marca);
                pro.X[x].setTipo(tipo);
                pro.X[x].setColor(color);
                pro.X[x].setAño(Integer.parseInt(año));
                pro.X[x].setPrecio(Integer.parseInt(precio));
                model.addRow(new Object[]{codigo,placa,marca,tipo,color,año,precio});
                contadorfin++;
            }else{
                 //CODIGO DESPUES
            }
        }
        eliminarCiclo=contadorfin;
            System.out.println("es . . . "+contadorfin);
        int tamanio=0;
        do {            
            tamanio++;
        } while (pro.X[tamanio]!=null);
            int eliminar=tamanio-(tamanio-cont); 
                for (int k = 1; k <=eliminar-1; k++) {
                    System.out.println("elimine"+ k);
                    model.removeRow(0);
                }
                    
        
        //Contar los que habian antes de iniciar la funcion eliminar y eliminar ese numero de los actuales.
        
       
         }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       int contadorfin=0;
        
        if (bandpri==1){
           contadorfin=0;
           
        
            for (int i = 1; i < pro.X.length-1; i++) {
            if (pro.X[i].getCodAuto()==null) {
                x=i;
            }
        }
           System.out.println("entre a cargar el archivo");
       System.out.println("x es " +x);
       String codigo,placa,marca,tipo,color,año,precio;
       String prueba1=getjTextField8().getText();
       int bandera=0;
       int cont=x;
        for (int i = 1; i <=x-1; i++) {
           //String prueba1=getjTextField8().getText();
           String prueba2=pro.X[i].getMarca();
            System.out.println("El registro " + pro.X[i].getMarca()+ " ES:"+prueba1+prueba2);
            if (prueba1.equals(prueba2)) {
                System.out.println("entre");
                codigo=pro.X[i].getCodAuto();
                placa=pro.X[i].getPlaca();
                marca=pro.X[i].getMarca();
                tipo=pro.X[i].getTipo();
                color=pro.X[i].getColor();
                año=""+pro.X[i].getAño();
                precio=""+pro.X[i].getPrecio();

                pro.X[x].setCodAuto(codigo);
                pro.X[x].setPlaca(placa);
                pro.X[x].setMarca(marca);
                pro.X[x].setTipo(tipo);
                pro.X[x].setColor(color);
                pro.X[x].setAño(Integer.parseInt(año));
                pro.X[x].setPrecio(Integer.parseInt(precio));
                model.addRow(new Object[]{codigo,placa,marca,tipo,color,año,precio});
                contadorfin++;
            }else{
                 //CODIGO DESPUES
            }
        }
        int tamanio=0;
        do {            
            tamanio++;
        } while (pro.X[tamanio]!=null);
           System.out.println("el tamaño es " + tamanio);
           System.out.println("el tamaño anterior es"+x);
           System.out.println("los que falta eliminar son"+eliminarCiclo);
            int eliminar=tamanio-cont-1; 
            System.out.println("ando elimnando" + eliminar);
                for (int k = 1; k <=eliminar+eliminarCiclo; k++) {
                    System.out.println("elimine"+ k);
                    model.removeRow(0);
                }
                   
        eliminarCiclo=0;
        eliminarCiclo=contadorfin;
        //Contar los que habian antes de iniciar la funcion eliminar y eliminar ese numero de los actuales.
  
       }else{
            
           contadorfin=0; 
           bandpri=1;
       System.out.println("entre a cargar el archivo");
       System.out.println("x es " +x);
       String codigo,placa,marca,tipo,color,año,precio;
       String prueba1=getjTextField8().getText();
       int bandera=0;
       int cont=x;
        for (int i = 1; i <=x-1; i++) {
           //String prueba1=getjTextField8().getText();
           String prueba2=pro.X[i].getMarca();
            System.out.println("El registro " + pro.X[i].getMarca()+ " ES:"+prueba1+prueba2);
            if (prueba1.equals(prueba2)) {
                System.out.println("entre");
                codigo=pro.X[i].getCodAuto();
                placa=pro.X[i].getPlaca();
                marca=pro.X[i].getMarca();
                tipo=pro.X[i].getTipo();
                color=pro.X[i].getColor();
                año=""+pro.X[i].getAño();
                precio=""+pro.X[i].getPrecio();

                pro.X[x].setCodAuto(codigo);
                pro.X[x].setPlaca(placa);
                pro.X[x].setMarca(marca);
                pro.X[x].setTipo(tipo);
                pro.X[x].setColor(color);
                pro.X[x].setAño(Integer.parseInt(año));
                pro.X[x].setPrecio(Integer.parseInt(precio));
                model.addRow(new Object[]{codigo,placa,marca,tipo,color,año,precio});
                contadorfin++;
            }else{
                 //CODIGO DESPUES
            }
        }
        eliminarCiclo=contadorfin;
            System.out.println("es . . . "+contadorfin);
        int tamanio=0;
        do {            
            tamanio++;
        } while (pro.X[tamanio]!=null);
            int eliminar=tamanio-(tamanio-cont); 
                for (int k = 1; k <=eliminar-1; k++) {
                    System.out.println("elimine"+ k);
                    model.removeRow(0);
                }
                    
        
        //Contar los que habian antes de iniciar la funcion eliminar y eliminar ese numero de los actuales.
        
       
         }
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autolotefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autolotefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autolotefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autolotefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autolotefrm().setVisible(true);
            }
        });
    }

    public ProyAutolote getPro() {
        return pro;
    }

    public void setPro(ProyAutolote pro) {
        this.pro = pro;
    }

    public DefaultTableModel getModel() {
        return model;
    }

    public void setModel(DefaultTableModel model) {
        this.model = model;
    }

    public JButton getGuardar() {
        return Guardar;
    }

    public void setGuardar(JButton Guardar) {
        this.Guardar = Guardar;
    }

    public JButton getInicializar() {
        return Inicializar;
    }

    public void setInicializar(JButton Inicializar) {
        this.Inicializar = Inicializar;
    }

    public JButton getLeerArchivo() {
        return LeerArchivo;
    }

    public void setLeerArchivo(JButton LeerArchivo) {
        this.LeerArchivo = LeerArchivo;
    }

    public JButton getNuevaLinea() {
        return NuevaLinea;
    }

    public void setNuevaLinea(JButton NuevaLinea) {
        this.NuevaLinea = NuevaLinea;
    }

    public JButton getVerRegistros() {
        return VerRegistros;
    }

    public void setVerRegistros(JButton VerRegistros) {
        this.VerRegistros = VerRegistros;
    }

    public JButton getjButton10() {
        return jButton10;
    }

    public void setjButton10(JButton jButton10) {
        this.jButton10 = jButton10;
    }

    public JButton getjButton11() {
        return jButton11;
    }

    public void setjButton11(JButton jButton11) {
        this.jButton11 = jButton11;
    }

    public JButton getjButton12() {
        return jButton12;
    }

    public void setjButton12(JButton jButton12) {
        this.jButton12 = jButton12;
    }

    public JButton getjButton13() {
        return jButton13;
    }

    public void setjButton13(JButton jButton13) {
        this.jButton13 = jButton13;
    }

    public JButton getjButton14() {
        return jButton14;
    }

    public void setjButton14(JButton jButton14) {
        this.jButton14 = jButton14;
    }

    public JButton getjButton15() {
        return jButton15;
    }

    public void setjButton15(JButton jButton15) {
        this.jButton15 = jButton15;
    }

    public JButton getjButton16() {
        return jButton16;
    }

    public void setjButton16(JButton jButton16) {
        this.jButton16 = jButton16;
    }

    public JButton getjButton17() {
        return jButton17;
    }

    public void setjButton17(JButton jButton17) {
        this.jButton17 = jButton17;
    }

    public JButton getjButton18() {
        return jButton18;
    }

    public void setjButton18(JButton jButton18) {
        this.jButton18 = jButton18;
    }

    public JButton getjButton19() {
        return jButton19;
    }

    public void setjButton19(JButton jButton19) {
        this.jButton19 = jButton19;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton20() {
        return jButton20;
    }

    public void setjButton20(JButton jButton20) {
        this.jButton20 = jButton20;
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JButton getjButton8() {
        return jButton8;
    }

    public void setjButton8(JButton jButton8) {
        this.jButton8 = jButton8;
    }

    public JButton getjButton9() {
        return jButton9;
    }

    public void setjButton9(JButton jButton9) {
        this.jButton9 = jButton9;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public void setjTextField8(JTextField jTextField8) {
        this.jTextField8 = jTextField8;
    }

    public JTextField getTxtaño() {
        return txtaño;
    }

    public void setTxtaño(JTextField txtaño) {
        this.txtaño = txtaño;
    }

    public JTextField getTxtcodigo() {
        return txtcodigo;
    }

    public void setTxtcodigo(JTextField txtcodigo) {
        this.txtcodigo = txtcodigo;
    }

    public JTextField getTxtcolor() {
        return txtcolor;
    }

    public void setTxtcolor(JTextField txtcolor) {
        this.txtcolor = txtcolor;
    }

    public JTextField getTxtmarca() {
        return txtmarca;
    }

    public void setTxtmarca(JTextField txtmarca) {
        this.txtmarca = txtmarca;
    }

    public JTextField getTxtplaca() {
        return txtplaca;
    }

    public void setTxtplaca(JTextField txtplaca) {
        this.txtplaca = txtplaca;
    }

    public JTextField getTxtprecio() {
        return txtprecio;
    }

    public void setTxtprecio(JTextField txtprecio) {
        this.txtprecio = txtprecio;
    }

    public JTextField getTxttipo() {
        return txttipo;
    }

    public void setTxttipo(JTextField txttipo) {
        this.txttipo = txttipo;
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Inicializar;
    private javax.swing.JButton LeerArchivo;
    private javax.swing.JButton NuevaLinea;
    private javax.swing.JButton VerRegistros;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
